### ISSUE TITLE
Extension Security, phase 1

### ISSUE THREAD

**Issue by Xarkam** [OSAMES/Base#1]
Cette extension gère le login et les droits.
Dans un premier temps :

-  elle possède une partie data layer
-  elle agit en tant que filtre http pour rediriger vers la page de login si on n'est pas authentifié
-  si on est authentifié, alors l'extension fournit un élément de menu "Logout". Relire le tuto sur les claims car on a le thread courant et la session. Etre authentifié = posséder une claim précise.

**Comment by Xarkam** [comment]
L'extension Security n'initialise aucun user.
Elle initialise toutes les tables concernant les "claims", les rôles, les droits, les repository, la base nécessaire dans la table users.

Voir https://github.com/Platformus/Platformus/tree/master/src/Platformus.Security.Data.Entities en exemple.

Penser à créer un extension "d'installation" qui permettra de mettre la base et les extensions fournies.

**Comment by postb99** [comment]
#4 features the work around permission manager module and unit testing, it was a lot of work and learning.
Next step is working on integrating http request interception, getting the authenticated state, logging in and off.

**Comment by postb99** [comment]
Détails techniques pour l'implémentation :

Réalisation des parties manquantes dans le module Security, et de la partie MVC dans le module Barebone.Security :
- Scope : page de login, l'authentification, si on est loggué on va sur le dashboard avec un message d'accueil.
- Réaliser notre UserManager (projet Security)
- Réaliser les ViewModel, Controller et vues (projet Barebone.Security)
- Réaliser l'interface IAuthorizationPolicyProvider, la modification de IExtensionMetadata (projet Infrastructure)
- Réaliser les 3 "Actions" dans Security.Actions, (projet Barebone.Security)

**Comment by Xarkam** [comment]
This issue was moved to SOFTINUX/Base#4
