### ISSUE TITLE
Extension d'initialisation

### ISSUE THREAD

**Issue by Xarkam** [OSAMES/Base#2]
Faire une extension qui va initialiser la base applicative et qui peut aussi initialiser un "package".

Un package est la base plus d'autres extensions.

**Comment by postb99** [comment]
Pour la base applicative "security" :
- credential types : "login". Prévoir aussi "google_oauth"?

**Comment by Xarkam** [comment]
Pour google auth ou l'OAuth en général, non pas dans l'immédiat. 
On avisera si il y a des demandent pour.

**Comment by Xarkam** [comment]
This issue was moved to SOFTINUX/Base#12
